jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Install Tauri CLI
      - name: Install Tauri CLI
        run: cargo install tauri-cli

      # Build the Tauri app
      - name: Build Tauri App
        run: cargo tauri build
